# Generated by Django 6.0 on 2025-12-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='area',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='division',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='house_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
